zExceptions-5.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
zExceptions-5.0.dist-info/LICENSE.txt,sha256=PmcdsR32h1FswdtbPWXkqjg-rKPCDOo_r1Og9zNdCjw,2070
zExceptions-5.0.dist-info/METADATA,sha256=zZwVDKzQkvCfFHEQWi1BwpD3_KI_UIxF6v2LIrk-OnU,3447
zExceptions-5.0.dist-info/RECORD,,
zExceptions-5.0.dist-info/WHEEL,sha256=pkctZYzUS4AYVn6dJ-7367OJZivF2e8RA9b_ZBjif18,92
zExceptions-5.0.dist-info/top_level.txt,sha256=zFCStwVrQuFYaKwnNCWmrJub2T8Yx4GRaQULvRThJrg,12
zExceptions/ExceptionFormatter.py,sha256=4DpqoS7XHnkxsQos4VygGe2umZpRBKPu-ucUij72HLI,7750
zExceptions/ITracebackSupplement.py,sha256=OIXWg_uqq3WKMHj8lbQh5ebfXrl9sx4W2x0n9lKxh7o,2684
zExceptions/TracebackSupplement.py,sha256=VExNFRsjhmgcDbfTNSMd5BGek0TaKSCK8abM1rnO3xo,1328
zExceptions/__init__.py,sha256=FF-pFr2LN2HE30tHHXZtf5KkiycXYHShyBdFuc6CQlo,11718
zExceptions/__pycache__/ExceptionFormatter.cpython-311.pyc,,
zExceptions/__pycache__/ITracebackSupplement.cpython-311.pyc,,
zExceptions/__pycache__/TracebackSupplement.cpython-311.pyc,,
zExceptions/__pycache__/__init__.cpython-311.pyc,,
zExceptions/__pycache__/unauthorized.cpython-311.pyc,,
zExceptions/tests/__init__.py,sha256=8pmNzrf_R6gngtAD-U4ztr27Y8n-S-ZHcarb_O4jnXE,36
zExceptions/tests/__pycache__/__init__.cpython-311.pyc,,
zExceptions/tests/__pycache__/testExceptionFormatter.cpython-311.pyc,,
zExceptions/tests/__pycache__/test___init__.cpython-311.pyc,,
zExceptions/tests/__pycache__/test_unauthorized.cpython-311.pyc,,
zExceptions/tests/testExceptionFormatter.py,sha256=YXJPfNwvwmYygQmOEq4hHODhvwqNTSfrJB4WSyNq7PU,4091
zExceptions/tests/test___init__.py,sha256=NYxbjMTxL-SLiFWaZQjj5utJmsAImFSEiQfSLi94JJ8,6867
zExceptions/tests/test_unauthorized.py,sha256=Ns_WOVocKDuqs4xbuqz-DHf2UyTSby-VqqmZa_3dQb8,4264
zExceptions/unauthorized.py,sha256=oGox41938GH7FnrCSgB-C6NjsF2qrarpOVafBlQqUrM,3352
